### ISSUE TITLE
Please, update project!

### ISSUE THREAD

**Issue by ipl-adm** [evonzee/StarryPy3k#13]
Hi! We still have a big community playing starbound with modpacks. It will be great, if u can make actual py3k proxy with working discord bot. I think, people from our server can donate you some, if it needed.

**Comment by evonzee** [comment]
Hi @ipl-adm 

Have you tried the python 3 branch? It theoretically works on Python 3, though I admittedly haven't tried the discord integration.

Rather than funding the project, what I really need is a community of testers since the group I played Starbound with has basically ceased to exist.  If you are an admin of a server with a group of players that wouldn't mind beta testing work, I am happy to implement features and upgrades the community needs.

**Comment by ipl-adm** [comment]
Thanks for reply! Yes, we have community server with big modpack and active players

**Comment by evonzee** [comment]
Sounds good. How can I get in touch with the server administrator? I would like to understand your hosting parameters (docker? If not, python version etc) so I know what to target. Ideally, a nonproduction instance with a test Starbound and test discord channel would be available.

**Comment by ipl-adm** [comment]
Im server admin. If you need: telegram: dpochuev email: derelanadecube@gmail.com or disocrd: borgir#2716
I give you all needed info about server and specs

**Comment by ipl-adm** [comment]
We also discussing here https://discord.gg/Cr7GaZCN

**Comment by evonzee** [comment]
I've got a branch that updates to the latest Python version and supports reading and writing Discord messages.  I've written to upstream to see if they are still taking PRs.  I will either send PRs to upstream or land them and continue this project as a disconnected fork if they don't respond in a few days.    Please open new tickets if additional work items are necessary.
